"""Initial user model

Revision ID: 649cfc34f4ef
Revises: 
Create Date: 2026-02-01 22:48:12.464127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649cfc34f4ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
